### ISSUE TITLE
dired-*-line shortcuts

### ISSUE THREAD

**Issue by pprevos** [protesilaos/dired-preview#1]
Hi Prot,

Interesting new package that is very useful for managing my collections of photographs.

I use arrow keys to navigate Dired buffers. You remap the `dired-*-line` functions to their `dired-preview-*` equivalents. But somehow, it only remaps the `p` and `n` keys, not the arrow or space keys that also map to the dried function.

Also, should PDFs be included as they are natively read by Emacs?

P:)

**Comment by protesilaos** [comment]
> From: Peter Prevos ***@***.***>
> Date: Sun, 25 Jun 2023 15:45:54 -0700
>
> Hi Prot,

Hello Peter,

> Interesting new package that is very useful for managing my
> collections of photographs.

Yes, this is my use-case as well!

> I use arrow keys to navigate Dired buffers. You remap the
> `dired-*-line` functions to their `dired-preview-*` equivalents. But
> somehow, it only remaps the `p` and `n` keys, not the arrow or space
> keys that also map to the dried function.

I was surprised when I noticed this.  I expected the remapping to apply
to all key bindings.  I don't know why it only picked one, let alone why
it picked that one.

At any rate, we are discussing this on the mailing list, with Christian
Tietze suggesting an alternative approach that may work more reliably:
<https://lists.sr.ht/~protesilaos/general-issues/%3Cm1zg4noej2.fsf%40christiantietze.de%3E>.

> Also, should PDFs be included as they are natively read by Emacs?

We can change the 'dired-preview-ignored-extensions-regexp' user option.
I don't have a strong opinion about it.  We already have previewing with
a delay, plus there is the max size limit.  Those help us avoid cases
where Emacs will take a long time to display the file.

All the best,
Prot

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by pprevos** [comment]
I'll follow the mailing list. Issue closed.
