### ISSUE TITLE
Would you like a preview placeholder PR?

### ISSUE THREAD

**Issue by xenodium** [protesilaos/dired-preview#14]
Great package Prot. Thank you!

Unsure if this is working as expected or misconfigruation on my part, but I found my eyes were a little more rested (no sudden window layout changes) when using a placeholder preview for ignored files.

I have a tiny patch, but wanted to prefly the idea before sending a PR...

Without patch:

![without-patch](https://github.com/user-attachments/assets/fb58eb5e-3405-4b2b-b6c2-e099e7d313ea)

With patch:

![with-patch](https://github.com/user-attachments/assets/5aba2c4c-8283-490c-a949-c09b53f0c1f3)

Is this of interest?

**Comment by protesilaos** [comment]
Hello @xenodium!

> Is this of interest?

Yes, this looks great. Maybe you can put it behind a `defcustom` in case someone prefers the old behaviour? But I am fine even without such an option.

**Comment by xenodium** [comment]
> Yes, this looks great. 

Great. Sent #15 PR.

>  Maybe you can put it behind a defcustom in case someone prefers the old behaviour?

Sounds good. Added `dired-preview-ignored-show-ignored-placeholders`.

**Comment by protesilaos** [comment]
I merged your PR. We can safely close this. Thank you!
