### ISSUE TITLE
window-width

### ISSUE THREAD

**Issue by artelse** [protesilaos/dired-preview#18]
On your dired-preview website in the example given to set window-width, there is no `width` property, it needs to be `window-width`. Thanks, very useful package!

**Comment by protesilaos** [comment]
> From: artelse ***@***.***>
> Date: Sun, 24 Nov 2024 05:47:39 -0800
>
> On your dired-preview website in the example given to set
> window-width, there is no `width` property, it needs to be
> `window-width`.

Thank you! Just for me to be sure, you mean this?

    (defun my-dired-preview-to-the-right ()
      "My preferred `dired-preview-display-action-alist-function'."
      '((display-buffer-in-side-window)
        (side . right)
        (width . 0.3)))

    (setq dired-preview-display-action-alist #'my-dired-preview-to-the-right)

> Thanks, very useful package!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by artelse** [comment]
Indeed, `window-width` is the right parameter.

**Comment by protesilaos** [comment]
Thank you! I just made the change.
