### ISSUE TITLE
possible typo in documentation, example "my-dired-preview-to-the-right ()"

### ISSUE THREAD

**Issue by rdiaz02** [protesilaos/dired-preview#19]
In https://protesilaos.com/emacs/dired-preview, current section "2.2. How to tweak the placement of the preview window", the `(defun my-dired-preview-to-the-right`, I think it should be `(window-width . 0.3)`  not `(width . 0.3)`.  (At least for me, Emacs 30, it is `window-width`).

(And great package, by the way! Thanks a lot!!! Creating custom functions that tweak the placement of the preview window  and the delay for different settings ---directories of photos vs directories of pdfs vs general usage, etc--- makes this really a swiss army knife that I can adapt, by calling a function, for pictures or general usage or .... .For example, in addition to the "regular use with dired", I think it is going to replace all of my possible needs of image-dired).

**Comment by protesilaos** [comment]
I just made the change. Thank you!

> And great package, by the way! Thanks a lot!!!

You are welcome! Let me know if there is anything else we can do with it either in the code or the manual (e.g. describe the workflow with regard to image-dired).

**Comment by rdiaz02** [comment]
My workflow is rather simple: by default, I don't enable dired-preview.  When I enter a directory with photos, I enable it and call a function that makes the window-width 0.8, which I like better. And I set the max size to 6 MB. For non-photos, my default is like in the documentation. I have a few functions to switch from one set of settings to the other (calling dired-preview if not running already).


This is all my code:

```elisp
(setq rdu-standard-dired-preview-delay 0.7)

(defun rdu-dired-preview-display-to-the-right ()
  "My preferred `dired-preview-display-action-alist-function'."
  '((display-buffer-in-side-window)
(side . right)
(window-width . 0.3)))

(defun rdu-dired-preview-display-photos ()
  "My preferred `dired-preview-display-action-alist-function' for photos."
  '((display-buffer-in-side-window)
(side . right)
(window-width . 0.8)
;; (preserve-size . (t . t))
))

(defun rdu-dired-preview-photos ()
  "RDU's standard settings for dired-preview."
  (interactive)
  (setq dired-preview-delay 0.0)
  (setq dired-preview-display-action-alist #'rdu-dired-preview-display-photos)
  (dired-preview-mode 1))

(defun rdu-dired-preview-default ()
  "Default settings for dired-preview"
  (interactive)
  (setq dired-preview-delay rdu-standard-dired-preview-delay)
  (setq dired-preview-display-action-alist #'rdu-dired-preview-display-to-the-right)
  (dired-preview-mode 1))

(setq dired-preview-display-action-alist #'my-dired-preview-to-the-right)
(setq dired-preview-delay rdu-standard-dired-preview-delay)
;; Seems fast enough and opens most photos
(setq dired-preview-max-size (* 6 1024 1024))
```
