### ISSUE TITLE
Add a variable to set the width of the Preview pane

### ISSUE THREAD

**Issue by ronniedroid** [protesilaos/dired-preview#3]
Right now the preview pane is set to a default width.

Make the preview pane width optional using a variable.

**Comment by ronniedroid** [comment]
I am actually working on this, I made a custom variable named `dired-preview-window-width`  which I am using inside the `dired-preview-display-action-alist`  like so

```lisp
(defcustom dired-preview-display-action-alist
  `((display-buffer-in-side-window)
    (side . right)
    (slot . -1)
    (window-width . ,dired-preview-window-width)
    (dedicated . t)
    ....
```
and it works well when I use either `setq` or `customize-set-variable` but only after a restart, not after evaluating the value, which means if the value is changed using the graphical customization interface, it won't be applied correctly until a restart to emacs. How can I fix this? will I need to use a hook?

I am sorry for my newbie question, this is my fist elisp contribution.

**Comment by protesilaos** [comment]
Hi @ronniedroid!  This is covered by the user option `dired-preview-display-action-alist-function`.  Granted, it is for experienced users.  I have not yet decided how best to make it accessible to less experienced users: it won't be easy, given that `display-buffer` is inherently complex.

At any rate, the primary goal at this stage is to have a stable core.  The extra features will be added later.

**Comment by ronniedroid** [comment]
Then I will wait for the stable version to come out then come back to this again.

**Comment by protesilaos** [comment]
As I noted before, there is a customisation option that covers this need.  This can be closed now.
